bug report issue templated created
commclassroom/commclassroom pull request #132
Opened 2021-09-27 05:45 UTC by harshmathurx

Bug report issue template added as mentioned in issue #129 
More issue templates can be added later by other contributors

2021-09-27 05:46 UTC, harshmathurx commented
hey, @kaiwalyakoparkar can you please review and mention any changes if required?

2021-09-27 06:36 UTC, kaiwalyakoparkar requested changes

2021-09-27 06:36 UTC, kaiwalyakoparkar commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: 'type: bug'
Hey I guess we don't have `type: bug` label so could you please change to one we have

2021-09-27 06:40 UTC, harshmathurx commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: 'type: bug'
We do right? check the second type
![image](https://user-images.githubusercontent.com/58532371/134856934-74711330-81b1-43c3-9a04-77046192a094.png)

2021-09-27 07:03 UTC, kaiwalyakoparkar commented
@harshmathurx Please enable `issues` tab on your forked repo so that I can check this template :)

2021-09-27 07:13 UTC, harshmathurx commented
> 
> 
> @harshmathurx Please enable `issues` tab on your forked repo so that I can check this template :)

just did

2021-09-28 05:06 UTC, kaiwalyakoparkar commented
@harshmathurx Please make sure you get yourself issue assigned before making a PR. If same behavior is found next time then your PR will have to be closed instantly. Hope you understand :slightly_smiling_face:

2021-09-28 05:09 UTC, harshmathurx commented
> @harshmathurx Please make sure you get yourself issue assigned before making a PR. If same behavior is found next time then your PR will have to be closed instantly. Hope you understand :slightly_smiling_face: 

I'm sorry, my bad 
I'll be mindful of that

2021-09-28 05:21 UTC, harshmathurx commented
> 
> 
> @harshmathurx We are requesting for issue template in `.yml` and not in `.md` could you please change that?

I'm not well versed with .yml files so I'm kinda confused

2021-09-28 05:23 UTC, closed without merging