Fix learn more link to open another tab
commclassroom/commclassroom pull request #196
Opened 2021-10-01 15:56 UTC by Neeteshking21

# Description
Fixes # 180

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] User Interface
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have ```npm run format``` before commiting
- [ ] I replicated the UI with the Design 

# ScreenShots (if any)

2021-10-01 16:05 UTC, Neeteshking21 commented
![bug_fix](https://user-images.githubusercontent.com/62437607/135652291-c37941f1-f952-491f-897d-afdc42276f76.gif)

2021-10-02 03:07 UTC, KamalSinghKhanna commented
thanks for the PR @Neeteshking21
LGTM!

2021-10-02 03:08 UTC, KamalSinghKhanna approved these changes
lgtm1

2021-10-02 03:08 UTC, KamalSinghKhanna commented
@kaiwalyakoparkar  can you please review this?

2021-10-02 04:46 UTC, kaiwalyakoparkar requested changes

2021-10-02 04:46 UTC, kaiwalyakoparkar commented on assets/css/style.css
> +    margin-left: 38px;
Please indent the this line of code

2021-10-02 04:46 UTC, kaiwalyakoparkar commented on assets/css/style.css
> +    margin: 2px 0 0 38px;
Please indent the this line of code as well

2021-10-02 06:28 UTC, Neeteshking21 reviewed
All fixed.

2021-10-02 06:29 UTC, Neeteshking21 commented
@kaiwalyakoparkar

2021-11-17 15:51 UTC, closed without merging