Added Task list to Readme.md
commclassroom/commclassroom pull request #51
Opened 2022-10-19 18:03 UTC by Raghav2305

## Fixes Issue

This PR fixes the following issues:

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots 
Add all the screenshots which support your changes

2022-10-20 07:05 UTC, kaiwalyakoparkar requested changes
@Raghav2305 I think you misunderstood the issue. We want to build the readme for the project and the task list in the issue is there to help you know all things you need to add. It seems like you copy pasted the things that were present in the issue description. Please make the changes accordingly

2022-10-20 22:51 UTC, shivam-sharma7 requested changes
I think here should be `Tittle` instead `Tilte`

2022-10-20 22:51 UTC, shivam-sharma7 commented on README.md
> +- [ ] Tilte
```suggestion
- [ ] Tittle
```
typo

2022-11-09 12:49 UTC, kaiwalyakoparkar commented
No changes, updates or conversation initiated. Hence closing :)

2022-11-09 12:49 UTC, closed without merging