Added designs on the buttons
commclassroom/commclassroom pull request #65
Opened 2022-10-23 05:24 UTC by bishal7679

Signed-off-by: Bishal Das <bishalhnj127@gmail.com>

## Fixes Issue #62

This PR fixes the following issues:

closes #62 

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots 
Add all the screenshots which support your changes

2022-10-23 06:21 UTC, AnuragThePathak requested changes

2022-10-23 06:21 UTC, AnuragThePathak commented on src/components/Blog.js
> +import React from "react";
Unnecessary changes and you are not following the code-style in the project. Replace by single quotes and remove the semis.

2022-10-23 13:12 UTC, AnuragThePathak commented on src/components/Blog.js
> +import React from "react";
Yeah I understand that, but the problem is that this project is still under work, so there are no style configuration files provided yet. For the time being, maybe you can update your vs code configuration to remove semi-colons in Javascript and prefer single quotes and it should solve the problem.

2022-10-23 14:14 UTC, bishal7679 commented
@AnuragThePathak Now all good to go!

2022-10-23 16:52 UTC, AnuragThePathak commented
Cool, rest of the changes would be reviewed by someone from the dev team.

2022-10-24 20:55 UTC, SuperAayush commented
Hey, @bishal7679 can you please quickly resolve the conflicts and commit ASAP 😄?

2022-10-25 04:44 UTC, bishal7679 commented
@SuperAayush This conflicts happened due to this PR https://github.com/commclassroom/commclassroom/pull/68

2022-10-25 05:43 UTC, SuperAayush commented
> @SuperAayush This conflicts happened due to this PR #68

Yes I am aware of that, #68 PR had the final changes for the homepage.
Can you please fetch the data, fix the conflicts and push the changes?

2022-10-25 06:04 UTC, bishal7679 commented
> > @SuperAayush This conflicts happened due to this PR #68
> 
> Yes I am aware of that, #68 PR had the final changes for the homepage. Can you please fetch the data, fix the conflicts and push the changes?

This final changes looks good! Actually I was facing some line-height issue for the Explore courses button. Now it is good to go!

2022-10-25 19:06 UTC, SuperAayush commented
> > > @SuperAayush This conflicts happened due to this PR #68
> > 
> > 
> > Yes I am aware of that, #68 PR had the final changes for the homepage. Can you please fetch the data, fix the conflicts and push the changes?
> 
> This final changes looks good! Actually I was facing some line-height issue for the Explore courses button. Now it is good to go!

Conflicts are yet to be solved!!

2022-10-25 19:28 UTC, bishal7679 commented
> > > > @SuperAayush This conflicts happened due to this PR #68
> > > 
> > > 
> > > Yes I am aware of that, #68 PR had the final changes for the homepage. Can you please fetch the data, fix the conflicts and push the changes?
> > 
> > 
> > This final changes looks good! Actually I was facing some line-height issue for the Explore courses button. Now it is good to go!
> 
> Conflicts are yet to be solved!!

@SuperAayush sure! I will push it soon!

2022-10-27 10:26 UTC, AnuragThePathak commented
@bishal7679 let us know if you need help in conflict resolution.

2022-10-28 05:03 UTC, bishal7679 commented
@AnuragThePathak @SuperAayush The page is not loading on localhost:3000

2022-10-28 05:46 UTC, AnuragThePathak commented
Maybe your site is crashing due to some errors.

2022-10-28 17:18 UTC, bhavyastar commented
Can you give the error message ? @bishal7679

2022-10-28 17:35 UTC, bishal7679 commented
@bhavyastar The page is loading with completely blank
![Screenshot (1457)](https://user-images.githubusercontent.com/70086051/198698133-bcd8543a-01d8-44bf-a04c-aa1e7e07a53a.png)
![Screenshot (1458)](https://user-images.githubusercontent.com/70086051/198698147-42892037-744d-4535-9732-f428d65cec3e.png)

2022-10-28 17:53 UTC, bishal7679 commented
@bhavyastar Now it is loading after run this command 
`npm audit fix --force`

2022-10-28 17:57 UTC, bishal7679 commented
@bhavyastar @SuperAayush The previous design of the site was looking quite good but in the current one
both side the space is looking so weird and so much blank!
WDYT?
Just giving my point of view :)

2022-10-28 18:56 UTC, closed without merging